### ISSUE TITLE
Find pearl by sign as fallback

### ISSUE THREAD

**Issue by pizzav-xyz** [EnderKill98/stasis-bot#1]
when it doesnt know whos pearl it is use the sign above it

**Comment by EnderKill98** [comment]
That sounds like a far too resource heavy task imo. Iterating over every block in some arbitrary range. Feel free to make a pr, but I don't know how to implement it sensibly and don't care about it tbh.

Also I consider signs over pearls a security issue. I prefer if people don't always know, who owns which pearl.
